This short introduction uses Keras to:

Build a neural network that classifies images.
Train this neural network.
And, finally, evaluate the accuracy of the model.

In [11]:
import pandas as pd
import numpy as np

In [12]:
import tensorflow as tf

In [13]:
# Load and prepare the MNIST dataset. Convert the samples from integers to floating-point numbers:

mnist = tf.keras.datasets.mnist

(x_train,y_train), (x_test,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0


In [14]:
mnist

<module 'tensorflow.keras.datasets.mnist' from 'C:\\Users\\Asus\\AppData\\Roaming\\Python\\Python37\\site-packages\\tensorflow\\keras\\datasets\\mnist\\__init__.py'>

In [15]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
    
])

For each example the model returns a vector of "logits" or "log-odds" scores, one for each class.

In [16]:
predictions = model(x_train[:1]).numpy()


In [17]:
predictions

array([[ 0.85480666,  0.28436685,  0.55803245, -0.12171025,  0.1801103 ,
         0.30748367, -0.19648926, -0.13836446, -0.06000577, -0.02869623]],
      dtype=float32)

In [18]:
# The tf.nn.softmax function converts these logits to "probabilities" for each class

tf.nn.softmax(predictions).numpy()

array([[0.1884401 , 0.1065208 , 0.1400509 , 0.07097042, 0.09597463,
        0.10901192, 0.0658569 , 0.06979826, 0.07548755, 0.07788842]],
      dtype=float32)

In [19]:
# The losses.SparseCategoricalCrossentropy loss takes a vector of logits and a True index and returns a scalar loss for each example.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
# This loss is equal to the negative log probability of the true class: It is zero if the model is sure of the correct class.

# This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.log(1/10) ~= 2.3.

loss_fn(y_train[:1], predictions).numpy()

2.216298

In [21]:
model.compile(optimizer='adam', loss=loss_fn,
             metrics=['accuracy'])

In [23]:
# The Model.fit method adjusts the model parameters to minimize the loss:
model.fit(x_train,y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 947us/step - loss: 0.4786 - accuracy: 0.8630
Epoch 2/5
1875/1875 [==============================] - 2s 910us/step - loss: 0.1528 - accuracy: 0.9555
Epoch 3/5
1875/1875 [==============================] - 2s 935us/step - loss: 0.1086 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - ETA: 0s - loss: 0.0897 - accuracy: 0.97 - 2s 933us/step - loss: 0.0897 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 2s 908us/step - loss: 0.0732 - accuracy: 0.9773


In [24]:
# The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".

model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0732 - accuracy: 0.9770


[0.07323525100946426, 0.9769999980926514]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [25]:
probabilty_model = tf.keras.Sequential([
    model, tf.keras.layers.Softmax()
])

In [26]:
probabilty_model

In [28]:
probabilty_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.97236199e-08, 1.80240782e-08, 1.31701090e-04, 2.21539769e-04,
        5.17457847e-11, 2.40065283e-08, 2.94967805e-12, 9.99646187e-01,
        2.50635033e-08, 5.05315370e-07],
       [1.30318263e-08, 3.41853706e-06, 9.99961019e-01, 1.93690121e-05,
        4.20143985e-16, 1.46905541e-06, 5.52933788e-09, 1.08193470e-13,
        1.47606661e-05, 2.88295473e-12],
       [2.14161247e-07, 9.99796212e-01, 4.67458158e-05, 5.39167195e-06,
        1.69472714e-05, 3.69569307e-06, 1.82172698e-06, 1.12031885e-04,
        1.52764987e-05, 1.78294283e-06],
       [9.99934673e-01, 6.12054984e-09, 5.46905103e-05, 6.73277839e-07,
        6.38140318e-10, 9.37751111e-07, 1.80146196e-06, 2.79351889e-06,
        1.28160039e-07, 4.25173403e-06],
       [5.03628712e-07, 2.07261386e-09, 3.15242892e-06, 6.23847711e-08,
        9.99365151e-01, 8.51231334e-08, 1.30896033e-05, 3.48007707e-05,
        2.48442262e-07, 5.82941168e-04]], dtype=float32)>